### ISSUE TITLE
Translated SNet module menu duplication

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/beast#20]
When running a translated version of BEAST (for instance german), the SNet right-mouse-button plugin menu contains duplicated categories. For instance, there are two entries in this menu called "Audio Quellen".

So some of the plugins that fit in this category are in the first submenu (XtalStrings) and some are in the second submenu (Standard-Oszillator). It appears to be the case that this is caused by the fact that some of the plugin categories have been translated and some don't. This makes the whole menu very unintuitive to use.

**Comment by tim-janik** [comment]
I managed to reproduce this here, using:

    LANGUAGE= LANG=de_DE.UTF-8 beast

The duplicate entries are due to a mixture of translated labels used in the menu paths. I.e. in one place we create a menu item "_Audio Quellen" from "/_Audio Sources/", in another place we refer to that menu entry as "/Audio Sources/XtalStrings". Some module names are translated, others not, and then the menu logic can not always properly join items, becuase the paths aren't translated piecewise.

Basically, there's no good way to fix this, other than redoing the path specifications during our next module migration. We need to split up the segments, so joining, translation and accelerator creation can be properly segmented. E.g.:

    -Info    category   = _("/Enhance/ArtsCompressor");
    +Info    menu_category   = "Enhance";
    +Info    module_title        = _("ArtsCompressor");

And *maybe* (just maybe), we shouldn't be translating the module names at all, since those are names after all. Or have a secondary title, to help beginners, e.g.:

    -Info    category  = _("/Audio Sources/DavOrgan");
    +Info    menu_category   = _("Audio Sources");    // DE: "Audio Quellen"
    +Info    module_name     = "DavOrgan";
    +Info    module_title        = _("synthetic organ");    // DE: "Synthetische Orgel";

Which becomes:

    EN: → Audio Sources → DavOrgan (synthetic organ)
    DE: → Audio Quellen → DavOrgan (Synthetische Orgel)

I'm happy to take patches towards implementing this. Short of someone else hacking on this, I'll probably address this at a later point when the plugin idl files need to be migrated.

**Comment by tim-janik** [comment]
Beast development is continued in [Anklang](github.com/tim-janik/anklang/)
