### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#48]
sorry to bother you but I have some questions about beat.

1 is beast going to be a full daw one day like pro tools, lmms or audor with audio and automation recording? I'm keyboard player that plays gutair , I runt it though synth like effects and have the effect change over time.
2. can use the modular window for unique audio processing?

**Comment by swesterfeld** [comment]
> is beast going to be a full daw one day like pro tools, lmms or audor with audio and automation recording? I'm keyboard player that plays gutair , I runt it though synth like effects and have the effect change over time.

I don't know. Automation for instance is a feature that I personally would like to use, so I hope BEAST eventually will support it. Audio recording is a feature that I personally don't need, so I wouldn't implement it, but if somebody contributes code to do it properly, this may become supported in BEAST in the future. 

> can use the modular window for unique audio processing?

Well you can use synthesis networks as effects. If you want to change the sound over time, BEAST doesn't 
 directly support automation, so the way to do it currently is to use a midi track (on some midi channel) and send midi events to change the parameters. I think PartyMonster has one example how to modulate one channel with another channel.

You can also use effects live, by letting BEAST just process the audio and pass it on (start with Stereo Through example and add effects as needed).

**Comment by tim-janik** [comment]
Hey @Reaper10.

Most DAW features are on our long-term todo list, full automation support and MIDI recording is definitely on it. I've just released 0.12.0-beta.1 which ships the start of a new UI that's much closer modeled to match well known DAWs.

Note that for general questions and discussions as well as catching related announcements, you might want to join our mailing list instead of posting on the issue tracker. Please take a look here:
  https://mail.gnome.org/archives/beast/
