### ISSUE TITLE
more plugin formats support

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#52]
vst 1 2 and 3 lv2  and au for mac plugin support

**Comment by swesterfeld** [comment]
Right. I definitely plan to implement at least VST2.4 and LV2 support for BEAST in the future. I haven't seriously look at VST3 yet, so I'm not sure how much extra work that would be.

**Comment by tim-janik** [comment]
This issue as currently formulated is very broad, e.g. definitely not useful to track @swesterfeld's VST-2 development intentions. And I trust that he'll be able to file his own PR if he has something that's useful to start a merge discussion on VST-2. Other than that, there hasn't been any input in the last 3 weeks here.

@Reaper10, it looks like a number of issues you're filing are general ideas or some sort of creative input you have on #DAW development. Filing feature requests without any follow up work isn't helpful in that case. You'd be better off starting a mailing list discussion [1] about your ideas, trying out Beast in it's current shape and maybe help with small scale improvement suggestions to particular Beast versions that are immediately actionable. The mailing list is a much better place for issues of "Wishlist" nature.

My focus for this issue tracker is on operational issues people have with existing Beast versions. Mainly because bug trackers are not good roadmap planning tools or brainstorming environments, which is why in the past I've rejected tracking other feature requests [2] here that weren't immediately or concretely actionable.

[1] https://beast.testbit.org/#support
[2] https://github.com/swesterfeld/beast/issues
