### ISSUE TITLE
more synth precution plugin

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#56]
could someone built in synthdrums  plugin and Mallets plugin
  Mallets - a struck-instrument synthesizer
        Is this necessary due to CMT 
http://www.ladspa.org/cmt/plugins.html
<img width="855" alt="capture" src="https://user-images.githubusercontent.com/8137561/43681121-a0c6737e-9810-11e8-9c39-9ce183ae10cc.PNG">

**Comment by tim-janik** [comment]
Please not that LADSPA v1 plugins are already supported, that includes cmt plugins released with a LADSPAv1 API. LADSPAv2 support is also planned, which could bring even more supported plugins.
Since there's no immediate action required on this bug and it's been sitting here for over 3 weeks, I'll close this in favour of other bugs that we actively work on.
