### ISSUE TITLE
audio recoding and audio i/o and tuner in beat

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#60]
I would love to see beast one day have audio recoding and audio i/o. 

PortAudio  will help with this 
http://www.portaudio.com/ 
Add internal audio waveform viewer / editor / audio recording and more #46 will also help

a Instrument Tuner widow would all so be great to be built into the audio track

http://gillesdegottex.github.io/fmit/index.html

https://github.com/gillesdegottex/fmit/

**Comment by tim-janik** [comment]
Thank you for your input.

Note, we've already had portaudio support in the past. That was discontinued due to limited interest on Linux.

Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.
