### ISSUE TITLE
libxml2 in a specific version wanted

### ISSUE THREAD

**Issue by magnetophon** [tim-janik/beast#63]
My version of libxml2 is too new:
```
checking for xmllint... /nix/store/b8bjqf3nwyjhc9dw08a5fiiyzqsml57c-libxml2-2.9.8-bin/bin/xmllint
configure: error: failed to detect version 20901: /nix/store/b8bjqf3nwyjhc9dw08a5fiiyzqsml57c-libxml2-2.9.8-bin/bin/xmllint --version
```
```
/nix/store/b8bjqf3nwyjhc9dw08a5fiiyzqsml57c-libxml2-2.9.8-bin/bin/xmllint: using libxml version 20908
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib
```

Does the code really need this specific version, or can the check be changed to a "newer than" check?

**Comment by tim-janik** [comment]
Hi, it's not exactly that your version is too new.
This is my system: 

$ xmllint --version
xmllint: using libxml version 20904

And Beast checks for 20901.
The problem is in the path you're using, out comparison macro picks up the "version" digits from the absolute pathname of your xmllint, and those won't match.
In any case, your xmllint is new enough, so you can hack the configure script to ignore the version check, I'll see if our macro can be made robus for cases like yours.

**Comment by magnetophon** [comment]
Thanks!

I've tried `sed '/XMLLINT/d' -i configure.ac` but it doesn't change anything.
Then I started experimenting with autogen, autoconf, and automake, but no luck yet.
Could you give me a pointer?
