### ISSUE TITLE
a metronome would be very helpful

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#70]
you could use
http://das.nasophon.de/gtklick/
http://das.nasophon.de/klick/
https://github.com/dsacre/gtklick
https://github.com/dsacre/klick

or
http://quitte.de/dsp/caps.html#Click
i'd think this would be easier

**Comment by swesterfeld** [comment]
Please explain: I would be interested in why do you need a metronome?

I currently can not think of one situation where you would benefit if we added a metronome today. Since BEAST currently cannot record midi nor record audio, where synchonization between the musician playing notes and the song tempo would be helpful.

**Comment by Reaper10** [comment]
for record midi audio and mid
