### ISSUE TITLE
Multi audio output module 

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#73]
To keep with module concept to beast, I have come with a Multi audio output module. This module should have unlimited audio puts.
it would  work  likes this
![multi audio output module](https://user-images.githubusercontent.com/8137561/44933093-6dad2f00-ad2d-11e8-9fdb-78aa00e5a0a8.png)
with a Multi audio output module a user could use it

1.with bes wave and Hydrogen import #41 and the Multi audio output module a user can rout the channels from Hydrogen drumkit to their own mix channel. this replaces Beast Hydrogen / universal drum machine #49  

2 this Multi audio output module should work any other modules to make a Multi audio output

3 the  module could use it, the bes wave could use it to become beast's version of in contac
 
4  it would all so help with building the Multi Instruments #55. 

5 This will all so be a great help in building a Multi audio Input effect for beast.

it's not just for drums but thats the most cowmen uses for it synth modules could use it, 

all out putts in the Multi audio output module are user defined 
. It will help with making a sample based instruments like this
 https://www.youtube.com/watch?v=fgcWwCgzPnE
This mite all so help with audio track device for parallel processing

**Comment by swesterfeld** [comment]
Right. If I understand this correctly, then you want this mainly for drum patterns. Currently we allow using the piano roll to sequence a drum patteren, for instance consisting of BD, SD and HH hits. What we currently do is downmix everything before the mixer, so the mixer only sees the mixed signal.

However, the downside of our current approach is that we cannot control the BD, SD and HH audio seperately, for instance change panning on HH only, make HH louder or eventually apply more reverb on the HH samples.

In Bitwig for instance, the drum machine output is split into sub-channels (two arrows symbol in the mixer), so each drum can be controlled in the mixer. It also allows for what our post-processing network on each sub-channel, so they can distort BD and keep SD/HH undistorted.

I am not even sure of how to add this to beast, could be tricky because it breaks existing assumptions of how tracks, busses and the mixer work.

**Comment by Reaper10** [comment]
it's not just for drums but thats the most cowmen uses for it

**Comment by tim-janik** [comment]
Thank you for your input.
Unfortunately there hasn't been any progress on this issue for several weeks, and it's not helpful to let this issue stay open without anyone volunteering to actively work on an implementation.
So it is now closed to avoid it cluttering our list of bugs that actually are being worked on.

@swesterfeld feel free to reopen this in your new-feature tracker.
