### ISSUE TITLE
add wav pack support

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/beast#76]
http://wavpack.com/

**Comment by swesterfeld** [comment]
Just one organizational remark: as you have noticed, @tim-janik wants to have only issues in the beast tracker that are directly relevant to the development right now. This means that feature requests that nobody is actively working on will be closed. This (and other requests by you) is such a feature request.

If you still want features that may or may not be implemented in the far future to be tracked, you can submit them to https://github.com/swesterfeld/beast  - so feel free to migrate your issues. Try to concentrate on the really important stuff, though, otherwise we'll have a huge list of feature requests and no way to navigate it sanely.
