### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [tim-janik/beast#90]
Thanks for making an AppImage. However, it was compiled on a "too new" system so that it won't run on Ubuntu 14.04, which is still a supported distribution at this point:

```
beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbse-0.so.13)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbse-0.so.13)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbse-0.so.13)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbse-0.so.13)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbse-0.so.13)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libpng16.so.16)
/run/firejail/appimage/.appimage-10323/usr/bin/beast-0.13.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-10323/usr/lib/libbsd.so.0)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1273

**Comment by tim-janik** [comment]
> Thanks for making an AppImage. However, it was compiled on a "too new" system so that it won't run on Ubuntu 14.04, which is still a supported distribution at this point

I'm fully aware of the AppImage Hub requirements regarding old distributions.

However there is no way that our code base will build on 14.04, at this point we have even given up on 16.04. For the moment, 18.04 is the base system that the AppImage builds require and our CI makes sure that they also run on Fedora-27. There are lots of third-party libraries and also the compilers that Beast depends on that simply aren't available in earlier distributions with the required feature set or bug fixes.

So I think this bug should actually be filed against the AppImage Hub for not allowing users the choice to pick AppImages built for newer distributions. Simply adding a new column to the Hub that lists the minimum supported distribution or Glibc version for an AppImage, instead of barring the AppImages from the site could allow a large number of new projects to get listed with their AppImages.

It's not like most Free Software projects have spare resources to invest into 5!!! years of LTS maintenance for free, so even if they bother to set up AppImage builds, the required base is most often too new to be listed.

IMHO, that's the *main* drawback in AppImage compared to snaps and flatpaks. There's no central place to find Apps from projects that can afford AppImage build maintenance but not free 5 year LTS services.

**Comment by probonopd** [comment]
Hi @tim-janik thanks for your feedback. I agree that it can be cumbersome to backport applications after the fact, so I am trying to establish a mindset that applications should be developed against the oldest still-supported distributions right from the outset.

In some cases this may not be desirable or feasible; for this cases there is the option to bundle _everything_ with the application, so that it will run on older systems than the one it was built on, too. We generally don't recommend this since it will make the AppImages larger than necessary and may have other downsides, but it is a possibility. Inkscape is using this method, for example. They are building on a very recent distribution yet their AppImage runs on distributions as old as 2012.

![dxjpg8dwwamie3s](https://user-images.githubusercontent.com/2480569/53149440-f9519b00-35ad-11e9-9deb-874002871247.jpg)

Please let me know if you are interested in trying this out, since our tools are currently not fully supporting this, so some manual steps are needed to make this work.

**Comment by tim-janik** [comment]
> Please let me know if you are interested in trying this out, since our tools are currently not fully supporting this, so some manual steps are needed to make this work.

Thank you for your input @probonopd, I frankly don't have the resources to attempt builds like this at the moment. Just to give you a rough idea, we're still in the 0.x development phase because major things still need to move around and dependencies fluctuate a lot. Some of the upcoming core functionality will have a strong dependency on C++17 (for which there's not sufficient support in 16.04), and in another bug report I just discovered that even Debian 9.8's components are too old to build a good working AppImage out of the box.

Since I'm quite busy with still shaping core functionality, efforts in porting the code base to other/older development environments will have to wait until it has stabelized to some extend and until I'm more idle.
